kind: Certificate
apiVersion: certmanager.k8s.io/v1alpha1
metadata:
  name: blog
spec:
  secretName: testesports-xyz-tls
  issuerRef:
    name: blog
  dnsNames:
    - testesports.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - testesports.xyz
